services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3ec2f4b136b5_key -iv $encrypted_3ec2f4b136b5_iv
  -in .env.enc -out .env -d
#- "./credentials.sh"
#- aws ssm get-parameters-by-path --region us-west-2 --with-decryption --path "/api/affinity/demo/"
  | jq -r '.Parameters[] | ([.Name, "\"" + .Value + "\""]) | join("=")' > /tmp/dev.affinity.ini
script:
#- docker exec affinity vendor/bin/phpunit
- vendor/bin/phpunit
- rm .env
