services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y python3.4
- sudo apt-get install -y jq
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- "./credentials.sh"
- aws ssm get-parameters-by-path --region us-west-2 --with-decryption --path "/api/affinity/demo/"
  | jq -r '.Parameters[] | ([.Name, "\"" + .Value + "\""]) | join("=")' > /tmp/demo.affinity.ini
- sed -i~ 's#/api/affinity/demo/##' /tmp/demo.affinity.ini
- mv /tmp/demo.affinity.ini .env
- docker build -t affinity .
- docker run --name affinity -d -v ${TRAVIS_BUILD_DIR}:/var/www affinity
script:
- docker exec affinity bash -c 'pwd && ls -la && composer install && vendor/bin/phpunit'
- rm .env
env:
  global:
  - DEPLOYMENT=us-west-2
  - secure: NCq+d+7myoDduzazJN1qxiLvMdg6Vg9IGO4/XGNysjuJT8f2AngqTr93i0SnBuUbwd3bJNJ347pyEPodQOhRRIyUDQjPK70IUmNRvl6DM0CRiyqTqqJWSoCIqCa+KROGalGZnH1jYkJ4MbWvd289Fd2DjRuxVxiI+uZlTPG4KKC+7rNYPl3DKR+mq94SlMmvMN4OKJscuaITjulZJw4ycmYVMDnS2YMUbnSRDq6AB1iKT2aMhQNjDuaAvP+b361lAcFpyGyFMBqrAUlLSa3f2I5CT07GYoYduuk1raR5LO5aO6ULoDm+Up4wPt5w/DlpPdeiVQ8GZJ89Uktno28JdSASr3Pf4pnmVcfP0JKyfaw0vV/RChZ8awJlPrNOXx0v4xyfWiGM56Hn2Ia4Ux64sBQRcBoR1SdRM+ylFF2F1cIlfqkqxfsWHElooIqRZjciQb8oLoBHDwOLi/2WW+UhGmL/v7D65g3/9ktm4+RxQfQI+g32eI6ULp0i+Tx2ftzq4ciF2WGMzaxJ5D0YYdlX2/ngSgIemFkuRO2KtLBtpZ34mnz7or+bYVmhaj2kP3Nngxjmx01jtqnm1OrXVH9jNH1wcx+pXUCtLgflh5mK6faUJT8O39ui8AitjNqNDiq8FLs7zglITlwwaDmSnwl7oOll0JbXtgVafcyQZRL9ANw=
